set(current_dir "${CMAKE_SOURCE_DIR}/cmake/packages/")

list(APPEND CMAKE_MODULE_PATH "${current_dir}")

include(threads)
if (IS_DEBUG)
    include(googletest)
    # include(fuzztest)
endif ()
include(zlib)
include(date)
# include(magic_enum)
# include(fixed_string)
include(json)
include(fmt)
include(brotli)
include(eve)
include(ctre)
include(boost)
