set(current_dir "${CMAKE_SOURCE_DIR}/cmake/packages/")

list(APPEND CMAKE_MODULE_PATH "${current_dir}")

include(threads)
include(googletest)
include(zlib)
include(date)
include(magic_enum)
include(fixed_string)
include(json)
include(fmt)
include(brotli)
include(eve)
include(ctre)
include(boost)
