name: Build
on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main
env:
  BUILD_TYPE: Debug
  CXX: /usr/bin/g++-12
  CC: /usr/bin/gcc-12
defaults:
  run:
    working-directory: ./build
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing Dependencies
        working-directory: ${{github.workspace}}
        run: sudo apt update && sudo apt install libboost-all-dev zlib1g-dev googletest
          g++-12 ninja-build
      - name: Configure CMake
        working-directory: ${{github.workspace}}
        run: cmake --preset=default
  tests:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build Tests
        run: cmake --build --preset tests
      - name: Test
        run: ctest --preset tests
  webpp-lib:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build Web++ Library
        run: cmake --build --preset webpp
  benchmarks:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build Benchmarks
        run: cmake --build --preset benchmarks
      - name: Run the executable
        run: ./webpp-benchmarks
  test-bodies:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-bodies
        run: cmake --build --preset test-bodies
      - name: Run test-bodies
        run: ./test-bodies
  test-cache:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-cache
        run: cmake --build --preset test-cache
      - name: Run test-cache
        run: ./test-cache
  test-charset:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-charset
        run: cmake --build --preset test-charset
      - name: Run test-charset
        run: ./test-charset
  test-concurrency:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-concurrency
        run: cmake --build --preset test-concurrency
      - name: Run test-concurrency
        run: ./test-concurrency
  test-const-list:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-const-list
        run: cmake --build --preset test-const-list
      - name: Run test-const-list
        run: ./test-const-list
  test-context:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-context
        run: cmake --build --preset test-context
      - name: Run test-context
        run: ./test-context
  test-convert:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-convert
        run: cmake --build --preset test-convert
      - name: Run test-convert
        run: ./test-convert
  test-cookies:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-cookies
        run: cmake --build --preset test-cookies
      - name: Run test-cookies
        run: ./test-cookies
  test-crypto:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-crypto
        run: cmake --build --preset test-crypto
      - name: Run test-crypto
        run: ./test-crypto
  test-dynamic-router:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-dynamic-router
        run: cmake --build --preset test-dynamic-router
      - name: Run test-dynamic-router
        run: ./test-dynamic-router
  test-extensions:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-extensions
        run: cmake --build --preset test-extensions
      - name: Run test-extensions
        run: ./test-extensions
  test-find-str:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-find-str
        run: cmake --build --preset test-find-str
      - name: Run test-find-str
        run: ./test-find-str
  test-functional:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-functional
        run: cmake --build --preset test-functional
      - name: Run test-functional
        run: ./test-functional
  test-header-accept-encoding:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-header-accept-encoding
        run: cmake --build --preset test-header-accept-encoding
      - name: Run test-header-accept-encoding
        run: ./test-header-accept-encoding
  test-http-parser:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-http-parser
        run: cmake --build --preset test-http-parser
      - name: Run test-http-parser
        run: ./test-http-parser
  test-ipv4:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-ipv4
        run: cmake --build --preset test-ipv4
      - name: Run test-ipv4
        run: ./test-ipv4
  test-ipv6:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-ipv6
        run: cmake --build --preset test-ipv6
      - name: Run test-ipv6
        run: ./test-ipv6
  test-istring:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-istring
        run: cmake --build --preset test-istring
      - name: Run test-istring
        run: ./test-istring
  test-json:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-json
        run: cmake --build --preset test-json
      - name: Run test-json
        run: ./test-json
  test-logger:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-logger
        run: cmake --build --preset test-logger
      - name: Run test-logger
        run: ./test-logger
  test-memory:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-memory
        run: cmake --build --preset test-memory
      - name: Run test-memory
        run: ./test-memory
  test-properties:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-properties
        run: cmake --build --preset test-properties
      - name: Run test-properties
        run: ./test-properties
  test-request:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-request
        run: cmake --build --preset test-request
      - name: Run test-request
        run: ./test-request
  test-response:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-response
        run: cmake --build --preset test-response
      - name: Run test-response
        run: ./test-response
  test-router:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-router
        run: cmake --build --preset test-router
      - name: Run test-router
        run: ./test-router
  test-routes:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-routes
        run: cmake --build --preset test-routes
      - name: Run test-routes
        run: ./test-routes
  test-server:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-server
        run: cmake --build --preset test-server
      - name: Run test-server
        run: ./test-server
  test-sql:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-sql
        run: cmake --build --preset test-sql
      - name: Run test-sql
        run: ./test-sql
  test-string:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-string
        run: cmake --build --preset test-string
      - name: Run test-string
        run: ./test-string
  test-traits:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-traits
        run: cmake --build --preset test-traits
      - name: Run test-traits
        run: ./test-traits
  test-tuple:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-tuple
        run: cmake --build --preset test-tuple
      - name: Run test-tuple
        run: ./test-tuple
  test-type-traits:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-type-traits
        run: cmake --build --preset test-type-traits
      - name: Run test-type-traits
        run: ./test-type-traits
  test-unicode:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-unicode
        run: cmake --build --preset test-unicode
      - name: Run test-unicode
        run: ./test-unicode
  test-uri-string:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-uri-string
        run: cmake --build --preset test-uri-string
      - name: Run test-uri-string
        run: ./test-uri-string
  test-uri:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-uri
        run: cmake --build --preset test-uri
      - name: Run test-uri
        run: ./test-uri
  test-ustring:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-ustring
        run: cmake --build --preset test-ustring
      - name: Run test-ustring
        run: ./test-ustring
  test-utils-casts:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-utils-casts
        run: cmake --build --preset test-utils-casts
      - name: Run test-utils-casts
        run: ./test-utils-casts
  test-utils-strings:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-utils-strings
        run: cmake --build --preset test-utils-strings
      - name: Run test-utils-strings
        run: ./test-utils-strings
  test-validations:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-validations
        run: cmake --build --preset test-validations
      - name: Run test-validations
        run: ./test-validations
  test-views:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build test-views
        run: cmake --build --preset test-views
      - name: Run test-views
        run: ./test-views
  example-cgi-hello-world:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build Example cgi-hello-world
        run: cmake --build --preset cgi-hello-world
      - name: Run Example cgi-hello-world
        run: ./cgi-hello-world
  example-cgi-application:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build Example cgi-application
        run: cmake --build --preset cgi-application
      - name: Run Example cgi-application
        run: ./cgi-application
  example-json-app:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build Example json-app
        run: cmake --build --preset json-app
      - name: Run Example json-app
        run: ./json-app
  example-beast-json:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build Example beast-json
        run: cmake --build --preset beast-json
      - name: Run Example beast-json
        run: ./beast-json
  example-beast-view:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build Example beast-view
        run: cmake --build --preset beast-view
      - name: Run Example beast-view
        run: ./beast-view
