/*
 * Created by moisrex on 11/04/22.
 * Initial source from: https://github.com/kainjow/Mustache.git
 *
 * Boost Software License - Version 1.0
 *
 * Mustache
 * Copyright 2015-2020 Kevin Wojniak
 * Copyright 2022-     Mohammad Bahoosh
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef WEBPP_MUSTACHE_VIEW_HPP
#define WEBPP_MUSTACHE_VIEW_HPP


#include "../convert/lexical_cast.hpp"
#include "../std/function_ref.hpp"
#include "../std/functional.hpp"
#include "../std/string_view.hpp"
#include "../strings/splits.hpp"
#include "../strings/trim.hpp"
#include "../traits/enable_traits.hpp"
#include "../traits/traits.hpp"
#include "html.hpp"
#include "view_concepts.hpp"

#include <array>
#include <map>
#include <span>
#include <variant>
#include <vector>

namespace webpp::views {

    /**
     * This struct is passwd to "lambda" that the user passes along with a text string.
     * The user (inside the lambda that they passed us) will call the operator()s in this renderer.
     */
    template <typename TraitsType>
    struct basic_renderer {
        using traits_type      = TraitsType;
        using string_view_type = traits::string_view<traits_type>;
        using string_type      = traits::general_string<traits_type>;

        using type = istl::function<string_type(string_view_type, bool escaped),
                                    traits::general_allocator<traits_type, stl::byte>>;

        constexpr string_type operator()(string_view_type text, bool escaped = false) const {
            return func(text, escaped);
        }

      private:
        explicit constexpr basic_renderer(type inp_func) noexcept : func{inp_func} {}

        type func;

        template <Traits>
        friend class mustache_view;
    };

    namespace details {
        template <Traits TraitsType>
        struct mustache_data_view_settings {
            using traits_type      = TraitsType;
            using string_type      = traits::general_string<traits_type>;
            using char_type        = traits::char_type<traits_type>;
            using string_view_type = traits::string_view<traits_type>;

            using renderer_type = basic_renderer<traits_type>;
            using lambda_type   = istl::function_ref<string_type(string_view_type, renderer_type const&)>;
            using partial_type  = istl::function_ref<string_type()>;


            template <typename V>
            static constexpr bool is_lambda = (
              requires(V v) { v(requires_arg_cvref(istl::StringView)); } ||
              requires(V v, renderer_type renderer) { v(requires_arg_cvref(istl::StringView), renderer); });

            template <typename Func>
            struct lambda_fixer : Func {
                using string_allocator_type = typename string_type::allocator_type;

                static constexpr bool requires_renderer =
                  requires(Func func, string_view_type text, renderer_type const& renderer) {
                      {
                          func(text, renderer)
                      } -> istl::StringViewifiableOf<string_type>;
                  };

              private:
                [[no_unique_address]] string_allocator_type string_allocator;

              public:
                // NOLINTBEGIN(cppcoreguidelines-pro-type-member-init)
                template <typename ET>
                    requires(!istl::cvref_as<ET, mustache_data_view_settings>)
                constexpr lambda_fixer(ET&& et, Func&& func) noexcept
                  : Func{stl::forward<Func>(func)},
                    string_allocator{alloc::general_allocator<char_type>(et)} {}

                // NOLINTEND(cppcoreguidelines-pro-type-member-init)

                constexpr string_type operator()(string_view_type text, renderer_type const& renderer) {
                    if constexpr (requires_renderer) {
                        return istl::stringify_of<string_type>(func(text, renderer), string_allocator);
                    } else if constexpr (requires(Func func) {
                                             {
                                                 func(text)
                                             } -> istl::StringViewifiableOf<string_type>;
                                         })
                    {
                        return istl::stringify_of<string_type>(func(text), string_allocator);
                    } else {
                        static_assert_false(Func,
                                            "We don't know how to call or handle the return type of the "
                                            "specified mustache lambda.");
                    }
                }
            };

            struct variable
              : stl::variant<bool,
                             lambda_type,
                             partial_type,
                             string_type,
                             stl::vector<variable, traits::general_allocator<traits_type, variable>>> {
                using variant_type =
                  stl::variant<bool,
                               lambda_type,
                               partial_type,
                               string_type,
                               stl::vector<variable, traits::general_allocator<traits_type, variable>>>;

                using list_type = stl::vector<variable, traits::general_allocator<traits_type, variable>>;

              private:
                string_type key_value;

                template <typename T, EnabledTraits ET>
                constexpr auto convert(T&& val, ET&& et) const {
                    using value_type = stl::remove_cvref_t<T>;
                    if constexpr (
                      istl::one_of<string_type,
                                   bool,
                                   lambda_type,
                                   partial_type,
                                   list_type,
                                   variant_type,
                                   value_type>)
                    {
                        return stl::forward<T>(val);
                    } else {
                        return lexical::cast<string_type>(stl::forward<T>(val),
                                                          alloc::general_alloc_for<string_type>(et));
                    }
                }

              public:
                template <EnabledTraits ET, typename StrT, typename T>
                    requires(istl::StringifiableOf<string_type, StrT>)
                constexpr variable(ET&& et, StrT&& input_key, T&& input_value)
                  : variant_type{convert(stl::forward<T>(input_value), et)},
                    key_value{istl::stringify_of<string_type>(stl::forward<StrT>(input_key),
                                                              alloc::general_allocator<char_type>(et))} {}

                template <EnabledTraits ET, typename StrT, typename T>
                constexpr variable(ET&& et, stl::pair<StrT, T> input)
                  : variant_type{convert(stl::move(input.second), et)},
                    key_value{istl::stringify_of<string_type>(stl::move(input.first),
                                                              alloc::general_allocator<char_type>(et))} {}

                [[nodiscard]] constexpr string_view_type key() const noexcept {
                    return istl::string_viewify_of<string_view_type>(key_value);
                }

                [[nodiscard]] constexpr bool is_false() const noexcept {
                    if (auto const* v = get_if_bool()) {
                        return *v;
                    }
                    if (auto const* vlist = get_if_list()) {
                        return vlist->empty();
                    }
                    return true;
                }

                // search the tree for a key and get a variable*
                // nullptr is returned if we couldn't find the key
                [[nodiscard]] constexpr variable const* get(string_view_type input_key) const noexcept {
                    if (key_value == input_key) {
                        return this;
                    }
                    if (auto list = get_if_list()) {
                        for (auto& item : *list) {
                            if (auto* var = item.get(input_key); var) {
                                return var;
                            }
                        }
                    }
                    return nullptr;
                }

                [[nodiscard]] constexpr variant_type const* as_variant() const noexcept {
                    return static_cast<variant_type const*>(this);
                }

                [[nodiscard]] constexpr string_type const* get_if_string() const {
                    return stl::get_if<string_type>(as_variant());
                }

                [[nodiscard]] constexpr lambda_type const* get_if_lambda() const {
                    return stl::get_if<lambda_type>(as_variant());
                }

                [[nodiscard]] constexpr list_type const* get_if_list() const {
                    return stl::get_if<list_type>(as_variant());
                }

                [[nodiscard]] constexpr bool const* get_if_bool() const {
                    return stl::get_if<bool>(as_variant());
                }

                [[nodiscard]] constexpr partial_type const* get_if_partial() const {
                    return stl::get_if<partial_type>(as_variant());
                }

                [[nodiscard]] constexpr bool is_string() const noexcept {
                    return stl::holds_alternative<string_type>(*as_variant());
                }

                [[nodiscard]] constexpr bool is_partial() const noexcept {
                    return stl::holds_alternative<partial_type>(*as_variant());
                }

                [[nodiscard]] constexpr bool is_lambda() const noexcept {
                    return stl::holds_alternative<lambda_type>(*as_variant());
                }

                [[nodiscard]] constexpr bool is_bool() const noexcept {
                    return stl::holds_alternative<bool>(*as_variant());
                }

                [[nodiscard]] constexpr partial_type const& partial_value() const noexcept {
                    return stl::get<partial_type>(*as_variant());
                }

                [[nodiscard]] constexpr string_type const& string_value() const noexcept {
                    return stl::get<string_type>(*as_variant());
                }

                [[nodiscard]] constexpr list_type const& list_value() const noexcept {
                    return stl::get<list_type>(*as_variant());
                }

                [[nodiscard]] constexpr bool is_non_empty_list() const noexcept {
                    if (auto const* list = get_if_list()) {
                        return list->empty();
                    }
                    return false;
                }
            };

            // data type
            using type = stl::vector<variable, traits::general_allocator<traits_type, variable>>;
        };

        enum class tag_type : stl::uint8_t {
            text,
            variable,
            unescaped_variable,
            section_begin,
            section_end,
            section_begin_inverted,
            comment,
            partial,
            set_delimiter
        };

        enum class render_lambda_escape : stl::uint8_t {
            escape,
            unescape,
            optional,
        };

    } // namespace details

    /**
     * A pair of delimiter type; in mustache you can change the delimiter you're using for variables and
     * stuff.
     */
    template <Traits TraitsType>
    struct delimiter_set {
        using traits_type = TraitsType;
        using string_type = traits::general_string<traits_type>;

        static constexpr auto default_begin = "{{";
        static constexpr auto default_end   = "}}";

        // NOLINTBEGIN(misc-non-private-member-variables-in-classes)
        string_type begin;
        string_type end;

        // NOLINTEND(misc-non-private-member-variables-in-classes)

        template <EnabledTraits ET>
        explicit constexpr delimiter_set(ET& et)
          : begin{default_begin, alloc::general_alloc_for<string_type>(et)},
            end{default_end, alloc::general_alloc_for<string_type>(et)} {}

        [[nodiscard]] constexpr bool is_default() const noexcept {
            return begin == default_begin && end == default_end;
        }
    };

    template <Traits TraitsType>
    struct context : enable_traits<TraitsType> {
        using traits_type      = TraitsType;
        using string_view_type = traits::string_view<traits_type>;
        using char_type        = traits::char_type<traits_type>;
        using data_type        = typename details::mustache_data_view_settings<traits_type>::type;
        using variable_type    = typename data_type::value_type;
        using items_type       = istl::vector<variable_type const*, traits_type>;
        using etraits          = enable_traits<traits_type>;

      private:
        items_type items{alloc::general_alloc_for<items_type>(*this)};

      public:
        template <EnabledTraits ET>
        context(ET&& et, variable_type const* data) : etraits{stl::forward<ET>(et)} {
            push(data);
        }

        ~context() = default;

        context(context const&)                = delete;
        context(context&&) noexcept            = default;
        context& operator=(context&&) noexcept = default;
        context& operator=(context const&)     = delete;

        template <EnabledTraits ET>
        context(ET&& et, data_type const* data) : etraits{stl::forward<ET>(et)} {
            items.reserve(data->size());
            stl::transform(stl::begin(*data),
                           stl::end(*data),
                           stl::back_inserter(items),
                           [](auto const& item) constexpr noexcept {
                               return &item;
                           });
        }

        void push(variable_type const* data) {
            items.insert(items.begin(), data);
        }

        void pop() {
            items.erase(items.begin());
        }

        variable_type const* get(string_view_type name) const {
            // process {{.}} name
            if (name.size() == 1 && name.at(0) == '.') {
                return items.front();
            }
            if (name.find('.') == string_view_type::npos) {
                // process normal name without having to split which is slower
                for (auto const& item : items) {
                    if (auto const var = item->get(name)) {
                        return var;
                    }
                }
                return nullptr;
            }
            // process x.y-like name
            auto names = object::make_local<stl::vector<string_view_type>>(*this);
            strings::basic_splitter<string_view_type, char_type>(name, char_type{'.'}).split(names);
            for (auto const* item : items) {
                auto* var = item;
                for (auto const& n : names) {
                    var = var->get(n);
                    if (!var) {
                        break;
                    }
                }
                if (var) {
                    return var;
                }
            }
            return nullptr;
        }

        variable_type const* get_partial(string_view_type name) const {
            for (auto const& item : items) {
                if (auto const var = item->get(name)) {
                    return var;
                }
            }
            return nullptr;
        }
    };

    template <Traits TraitsType>
    struct line_buffer_state {
        using traits_type = TraitsType;
        using string_type = traits::general_string<traits_type>;

        // NOLINTBEGIN(misc-non-private-member-variables-in-classes)
        string_type data;
        bool        contained_section_tag = false;

        // NOLINTEND(misc-non-private-member-variables-in-classes)

        template <EnabledTraits ET>
        explicit constexpr line_buffer_state(ET& et) : data{alloc::general_alloc_for<string_type>(et)} {}

        [[nodiscard]] constexpr bool is_empty_or_contains_only_whitespace() const noexcept {
            for (auto const cur_char : data) {
                // don't look at newlines
                if (cur_char != ' ' && cur_char != '\t') {
                    return false;
                }
            }
            return true;
        }

        constexpr void clear() {
            data.clear();
            contained_section_tag = false;
        }
    };

    template <Traits TraitsType>
    struct context_internal {
        using traits_type = TraitsType;

        // NOLINTBEGIN(misc-non-private-member-variables-in-classes)
        context<traits_type>*          ctx = nullptr;
        delimiter_set<traits_type>     delim_set;
        line_buffer_state<traits_type> line_buffer;

        // NOLINTEND(misc-non-private-member-variables-in-classes)

        explicit constexpr context_internal(context<traits_type>& ctx_ref)
          : ctx{&ctx_ref},
            delim_set{ctx_ref},
            line_buffer{ctx_ref} {}

        constexpr context_internal(context_internal const&)                = default;
        constexpr context_internal(context_internal&&) noexcept            = default;
        constexpr context_internal& operator=(context_internal&&) noexcept = default;
        constexpr context_internal& operator=(context_internal const&)     = default;

        constexpr ~context_internal() = default;

        template <EnabledTraits ET>
        explicit constexpr context_internal(ET& et)
          : delim_set{et},
            line_buffer{et} {}
    };

    template <Traits TraitsType>
    struct mstch_tag /* gcc doesn't allow "tag tag;" so rename the class :( */ {
        using traits_type = TraitsType;
        using string_type = traits::general_string<traits_type>;

        // NOLINTBEGIN(misc-non-private-member-variables-in-classes)

        // the name cannot be a string view
        string_type                name;
        details::tag_type          type         = details::tag_type::text;
        stl::optional<string_type> section_text = stl::nullopt;
        delimiter_set<traits_type> delim_set;

        // NOLINTEND(misc-non-private-member-variables-in-classes)

        template <EnabledTraits ET>
        explicit constexpr mstch_tag(ET& et)
          : name{alloc::general_alloc_for<string_type>(et)},
            delim_set{et} {}

        [[nodiscard]] constexpr bool is_section_begin() const noexcept {
            using enum details::tag_type;
            return type == section_begin || type == section_begin_inverted;
        }

        [[nodiscard]] constexpr bool is_section_end() const noexcept {
            return type == details::tag_type::section_end;
        }
    };

    template <Traits TraitsType>
    struct context_pusher {
        using traits_type   = TraitsType;
        using data_type     = typename details::mustache_data_view_settings<traits_type>::type;
        using variable_type = typename data_type::value_type;

        constexpr context_pusher(context_internal<traits_type>& ctx, variable_type const* var) : ctx_(&ctx) {
            ctx.ctx->push(var);
        }

        constexpr ~context_pusher() {
            ctx_->ctx->pop();
        }

        constexpr context_pusher(context_pusher const&)                = delete;
        constexpr context_pusher(context_pusher&&) noexcept            = default;
        constexpr context_pusher& operator=(context_pusher const&)     = delete;
        constexpr context_pusher& operator=(context_pusher&&) noexcept = default;

      private:
        context_internal<traits_type>* ctx_;
    };

    template <Traits TraitsType>
    struct component {
        using traits_type      = TraitsType;
        using string_type      = traits::general_string<traits_type>;
        using string_view_type = traits::string_view<traits_type>;
        using string_size_type = typename string_view_type::size_type;

        using children_type = traits::generalify_allocators<traits_type, stl::vector<component>>;

        // NOLINTBEGIN(misc-non-private-member-variables-in-classes)

        // the reason why this can't be a string view is because of whitespaces that get ignored during the
        // parsing
        string_type            text;
        mstch_tag<traits_type> tag;
        children_type          children;
        string_size_type       position = string_view_type::npos;

        // NOLINTEND(misc-non-private-member-variables-in-classes)

        enum class walk_control : stl::uint8_t {
            walk, // "continue" is reserved :/
            stop,
            skip,
        };

        // NOLINTBEGIN(bugprone-forwarding-reference-overload)
        template <EnabledTraits ET>
            requires(!stl::same_as<stl::remove_cvref_t<ET>, component>)
        explicit constexpr component(ET&&             et,
                                     string_view_type inp_text = "",
                                     string_size_type inp_pos  = string_view_type::npos)
          : text(inp_text, alloc::general_alloc_for<string_type>(et)),
            tag{et},
            children{alloc::general_allocator<component>(et)},
            position(inp_pos) {}

        // NOLINTEND(bugprone-forwarding-reference-overload)

        [[nodiscard]] constexpr bool is_text() const noexcept {
            return tag.type == details::tag_type::text;
        }

        [[nodiscard]] constexpr bool is_newline() const noexcept {
            return is_text() && ((text.size() == 2 && text[0] == '\r' && text[1] == '\n') ||
                                 (text.size() == 1 && (text[0] == '\n' || text[0] == '\r')));
        }

        [[nodiscard]] constexpr bool is_non_newline_whitespace() const noexcept {
            return is_text() && !is_newline() && text.size() == 1 && (text[0] == ' ' || text[0] == '\t');
        }

        template <typename WalkCallback>
        constexpr void walk_children(WalkCallback&& callback) {
            for (auto& child : children) {
                if (child.walk(callback) != walk_control::walk) {
                    break;
                }
            }
        }

      private:
        template <typename WalkCallback>
        constexpr walk_control walk(WalkCallback&& callback) {
            walk_control control{callback(*this)};
            if (control == walk_control::stop) {
                return control;
            }
            if (control == walk_control::skip) {
                return walk_control::walk;
            }
            for (auto& child : children) {
                control = child.walk(callback);
                if (control == walk_control::stop) {
                    return control;
                }
            }
            return control;
        }
    };

    template <Traits TraitsType>
    struct mustache_view : enable_traits<TraitsType> {
        using etraits          = enable_traits<TraitsType>;
        using traits_type      = TraitsType;
        using string_type      = traits::general_string<traits_type>;
        using string_view_type = traits::string_view<traits_type>;
        using char_type        = typename string_type::value_type;

        using string_size_type  = typename string_type::size_type;
        using component_type    = component<traits_type>;
        using walk_control_type = typename component_type::walk_control;

        using settings      = details::mustache_data_view_settings<traits_type>;
        using data_type     = typename settings::type;
        using variable_type = typename settings::variable;
        using lambda_type   = typename settings::lambda_type;
        using partial_type  = typename settings::partial_type;


        using render_handler = istl::function<
          void(string_view_type),
          traits::general_allocator<traits_type, stl::byte>>; // todo: see if we need this handler
        using renderer_type = basic_renderer<traits_type>;

        static constexpr auto MUSTACHE_CAT = "MustacheView";

      private:
        string_type    error_msg{alloc::general_alloc_for<string_type>(*this)};
        component_type root_component;

      public:
        // NOLINTBEGIN(bugprone-forwarding-reference-overload)
        template <EnabledTraits ET>
            requires(!stl::same_as<stl::remove_cvref_t<ET>, mustache_view>)
        explicit constexpr mustache_view(ET&& et) noexcept
          : etraits{et},
            root_component{et} {}

        // NOLINTEND(bugprone-forwarding-reference-overload)

        constexpr mustache_view(mustache_view const&)     = default;
        constexpr mustache_view(mustache_view&&) noexcept = default;
        constexpr ~mustache_view() noexcept               = default;

        constexpr mustache_view& operator=(mustache_view const&)     = default;
        constexpr mustache_view& operator=(mustache_view&&) noexcept = default;

        constexpr void scheme(string_view_type input) {
            delimiter_set<traits_type> delim_set{*this};
            parse(input, delim_set);
        }

        // check if we have previously parsed the scheme, and it's ready for multiple render calls
        [[nodiscard]] constexpr bool has_scheme() const noexcept {
            return root_component.children.size() > 0;
        }

        [[nodiscard]] constexpr bool is_valid() const noexcept {
            return error_msg.empty();
        }

        [[nodiscard]] constexpr string_view_type error_message() const noexcept {
            return error_msg;
        }

        template <typename stream_type>
        constexpr stream_type& render(data_type const& data, stream_type& stream) {
            render(data, [&stream](string_view_type str) {
                stream << str;
            });
            return stream;
        }

        constexpr string_type render(data_type const& data) {
            stl::basic_ostringstream<typename string_type::value_type> oss;
            return render(data, oss).str();
        }

        template <typename stream_type>
        constexpr stream_type& render(context<traits_type>& ctx, stream_type& stream) {
            context_internal<traits_type> context{ctx};
            render(
              [&stream](string_view_type str) {
                  stream << str;
              },
              context);
            return stream;
        }

        constexpr string_type render(context<traits_type>& ctx) {
            stl::basic_ostringstream<typename string_type::value_type> oss;
            return render(ctx, oss).str();
        }

        constexpr void render(data_type const& data, render_handler const& handler) {
            if (!is_valid()) {
                return;
            }
            context<traits_type>          ctx{*this, &data};
            context_internal<traits_type> context{ctx};
            render(handler, context);
        }

        template <typename DT = data_type>
            requires(PossibleDataTypes<mustache_view, stl::remove_cvref_t<DT>>)
        constexpr void render(string_type& out, DT&& data) {
            if (!is_valid()) {
                return;
            }
            if constexpr (istl::cvref_as<DT, data_type>) {
                context<traits_type>          ctx{*this, &data};
                context_internal<traits_type> context{ctx};
                // todo: optimization chance: out::reserve
                render(
                  [&]<typename ContentT>(ContentT&& content) {
                      out += stl::forward<ContentT>(content);
                  },
                  context);
            } else if constexpr (stl::same_as<DT, data_type> || istl::Collection<DT>) {
                auto data_vec = object::make_general<data_type>(this->alloc_pack);
                data_vec.reserve(data.size());
                stl::transform(stl::begin(data),
                               stl::end(data),
                               stl::back_inserter(data_vec),
                               [this](auto&& item) -> variable_type {
                                   auto const& [key, value] = item;
                                   return variable_type{*this, key, value};
                               });
                render<data_type>(out, data_vec);
            } else {
                this->logger.error(
                  MUSTACHE_CAT,
                  "We don't understand the data you passed the mustache renderer, we're gonna ignore them.");
            }
        }

      private:
        [[nodiscard]] constexpr auto escaper(string_view_type val) {
            string_type out{alloc::general_alloc_for<string_type>(*this)};
            html_escape(val, out);
            return out;
        }

        /////// Parser


        static constexpr stl::array<string_view_type, 5> whitespace{
          {"\r\n", "\n", "\r", " ", "\t"}
        };

        constexpr void parse(string_view_type input, delimiter_set<traits_type>& delim_set) {
            using streamstring = stl::basic_ostringstream<typename string_type::value_type>;

            string_view_type const brace_delimiter_end_unescaped("}}}");
            string_size_type const input_size{input.size()};

            bool current_delimiter_is_brace{delim_set.is_default()};

            using sections_type       = stl::vector<component_type*>;
            using section_starts_type = stl::vector<string_size_type>;

            auto sections       = object::make_local<sections_type>(this->alloc_pack, &root_component);
            auto section_starts = object::make_local<section_starts_type>(this->alloc_pack);

            auto             current_text          = object::make_local<string_type>(this->alloc_pack);
            string_size_type current_text_position = string_type::npos;

            current_text.reserve(input_size);

            // NOLINTBEGIN(*-macro-usage, *-avoid-do-while)
#define process_current_text()                                                     \
    do {                                                                           \
        if (!current_text.empty()) {                                               \
            const component_type comp{*this, current_text, current_text_position}; \
            sections.back()->children.push_back(comp);                             \
            current_text.clear();                                                  \
            current_text_position = string_type::npos;                             \
        }                                                                          \
    } while (false)
            // NOLINTEND(*-macro-usage, *-avoid-do-while)


            for (string_size_type input_position = 0; input_position != input_size;) {
                bool parse_tag = false;

                if (input.compare(input_position, delim_set.begin.size(), delim_set.begin) == 0) {
                    process_current_text();

                    // Tag start delimiter
                    parse_tag = true;
                } else {
                    bool parsed_whitespace = false;
                    for (auto const& whitespace_text : whitespace) {
                        if (input.compare(input_position, whitespace_text.size(), whitespace_text) == 0) {
                            process_current_text();

                            component_type const comp{*this, whitespace_text, input_position};
                            sections.back()->children.push_back(comp);
                            input_position += whitespace_text.size();

                            parsed_whitespace = true;
                            break;
                        }
                    }

                    if (!parsed_whitespace) {
                        if (current_text.empty()) {
                            current_text_position = input_position;
                        }
                        current_text.append(1, input[input_position]);
                        ++input_position;
                    }
                }

                if (!parse_tag) {
                    continue;
                }

                // Find the next tag start delimiter
                string_size_type const tag_location_start = input_position;

                // Find the next tag end delimiter
                string_size_type tag_contents_location{tag_location_start + delim_set.begin.size()};
                bool const       tag_is_unescaped_var{
                  current_delimiter_is_brace && tag_location_start != (input_size - 2) &&
                  input.at(tag_contents_location) == delim_set.begin.at(0)};
                string_view_type const current_tag_delimiter_end{
                  tag_is_unescaped_var ? brace_delimiter_end_unescaped : delim_set.end};
                auto const current_tag_delimiter_end_size = current_tag_delimiter_end.size();
                if (tag_is_unescaped_var) {
                    ++tag_contents_location;
                }
                string_size_type const tag_location_end{
                  input.find(current_tag_delimiter_end, tag_contents_location)};
                if (tag_location_end == string_view_type::npos) {
                    streamstring oss;
                    oss << "Unclosed tag at " << tag_location_start;
                    error_msg.assign(oss.str());
                    return;
                }

                // Parse tag
                string_view_type tag_contents =
                  input.substr(tag_contents_location, tag_location_end - tag_contents_location);
                ascii::trim(tag_contents);
                component_type comp{*this};
                if (!tag_contents.empty() && tag_contents[0] == '=') {
                    if (!parse_set_delimiter_tag(tag_contents, delim_set)) {
                        streamstring oss;
                        oss << "Invalid set delimiter tag at " << tag_location_start;
                        error_msg.assign(oss.str());
                        return;
                    }
                    current_delimiter_is_brace = delim_set.is_default();
                    comp.tag.type              = details::tag_type::set_delimiter;
                    comp.tag.delim_set         = delim_set;
                }
                if (comp.tag.type != details::tag_type::set_delimiter) {
                    parse_tag_contents(tag_is_unescaped_var, tag_contents, comp.tag);
                }
                comp.position = tag_location_start;
                sections.back()->children.push_back(comp);

                // Start next search after this tag
                input_position = tag_location_end + current_tag_delimiter_end_size;

                // Push or pop sections
                if (comp.tag.is_section_begin()) {
                    sections.push_back(&sections.back()->children.back());
                    section_starts.push_back(input_position);
                } else if (comp.tag.is_section_end()) {
                    if (sections.size() == 1) {
                        streamstring oss;
                        oss << "Unopened section \"" << comp.tag.name << "\" at " << comp.position;
                        error_msg.assign(oss.str());
                        return;
                    }
                    sections.back()->tag.section_text = string_type{
                      input.substr(section_starts.back(), tag_location_start - section_starts.back()),
                      alloc::general_alloc_for<string_type>(*this)};
                    sections.pop_back();
                    section_starts.pop_back();
                }
            }

            process_current_text();

            // Check for sections without an ending tag
            root_component.walk_children([this](component_type& comp) -> walk_control_type {
                if (!comp.tag.is_section_begin()) {
                    return walk_control_type::walk;
                }
                if (comp.children.empty() || !comp.children.back().tag.is_section_end() ||
                    comp.children.back().tag.name != comp.tag.name)
                {
                    streamstring oss;
                    oss << "Unclosed section \"" << comp.tag.name << "\" at " << comp.position;
                    error_msg.assign(oss.str());
                    return walk_control_type::stop;
                }
                comp.children.pop_back(); // remove now useless end section component
                return walk_control_type::walk;
            });

            // fixme: what am I looking here?
            if (!error_msg.empty()) {
                return;
            }
#undef process_current_text
        }

        constexpr bool is_set_delimiter_valid(string_view_type delimiter) const {
            // "Custom delimiters may not contain whitespace or the equals sign."
            // todo: optimize-able
            for (auto const cur_char : delimiter) {
                if (cur_char == '=' || stl::isspace(cur_char)) {
                    return false;
                }
            }
            return true;
        }

        [[nodiscard]] constexpr bool parse_set_delimiter_tag(
          string_view_type            contents,
          delimiter_set<traits_type>& delimiter_set) const {
            // Smallest legal tag is "=X X="
            constexpr stl::size_t smallest_legal_tag_size = 5;
            if (contents.size() < smallest_legal_tag_size) {
                return false;
            }
            if (contents.back() != '=') {
                return false;
            }
            contents = contents.substr(1, contents.size() - 2); // todo: use remove_prefix and remove_suffix
            ascii::trim(contents);
            auto const spacepos = contents.find(' ');
            if (spacepos == string_view_type::npos) {
                return false;
            }
            auto const nonspace = contents.find_first_not_of(' ', spacepos + 1);
            assert(nonspace != string_type::npos);
            auto const begin = contents.substr(0, spacepos);
            auto const end   = contents.substr(nonspace, contents.size() - nonspace);
            if (!is_set_delimiter_valid(begin) || !is_set_delimiter_valid(end)) {
                return false;
            }
            delimiter_set.begin = begin;
            delimiter_set.end   = end;
            return true;
        }

        constexpr void parse_tag_contents(
          bool                    is_unescaped_var,
          string_view_type        contents,
          mstch_tag<traits_type>& tag) const {
            using enum details::tag_type;
            if (is_unescaped_var) {
                tag.type = unescaped_variable;
                tag.name = contents;
            } else if (contents.empty()) {
                tag.type = variable;
                tag.name = {};
            } else {
                switch (contents.at(0)) {
                    case '#': tag.type = section_begin; break;
                    case '^': tag.type = section_begin_inverted; break;
                    case '/': tag.type = section_end; break;
                    case '>': tag.type = partial; break;
                    case '&': tag.type = unescaped_variable; break;
                    case '!': tag.type = comment; break;
                    default: tag.type = variable; break;
                }
                if (tag.type == variable) {
                    tag.name = contents;
                } else {
                    tag.name = contents;
                    tag.name.erase(0, 1); // remove the first char
                    ascii::trim(tag.name);
                }
            }
        }

        ////// Renderer





        constexpr string_type render(context_internal<traits_type>& ctx) {
            auto out = object::make_general<string_type>(*this);
            // todo: optimization chance: out::reserve
            render(
              [&]<typename ContentT>(ContentT&& content) {
                  out += stl::forward<ContentT>(content);
              },
              ctx);
            return out;
        }

        constexpr void
        render(render_handler const& handler, context_internal<traits_type>& ctx, bool root_renderer = true) {
            root_component.walk_children([&handler, &ctx, this](component_type& comp) -> walk_control_type {
                return render_component(handler, ctx, comp);
            });
            // process the last line, but only for the top-level renderer
            if (root_renderer) {
                render_current_line(handler, ctx.line_buffer, nullptr);
            }
        }

        constexpr void render_current_line(
          render_handler const&           handler,
          line_buffer_state<traits_type>& line_buffer,
          component_type const*           comp) const {
            // We're at the end of a line, so check the line buffer state to see
            // if the line had tags in it, and also if the line is now empty or
            // contains whitespace only. if this situation is true, skip the line.
            if (!line_buffer.contained_section_tag && !line_buffer.is_empty_or_contains_only_whitespace()) {
                handler(line_buffer.data);
                if (comp) {
                    handler(comp->text);
                }
            }
            line_buffer.clear();
        }

        constexpr walk_control_type render_component(
          render_handler const&          handler,
          context_internal<traits_type>& ctx,
          component_type&                comp) {
            if (comp.is_text()) {
                if (comp.is_newline()) {
                    render_current_line(handler, ctx.line_buffer, &comp);
                } else {
                    ctx.line_buffer.data.append(comp.text);
                }
                return walk_control_type::walk;
            }

            mstch_tag<traits_type> const& tag{comp.tag};
            variable_type const*          var; // NOLINT(cppcoreguidelines-init-variables)
            switch (tag.type) {
                using enum details::tag_type;
                case variable:
                case unescaped_variable:
                    var = ctx.ctx->get(tag.name);
                    if (var != nullptr) {
                        if (!render_variable(handler, var, ctx, tag.type == variable)) {
                            return walk_control_type::stop;
                        }
                    }
                    break;
                case section_begin:
                    var = ctx.ctx->get(tag.name);
                    if (var != nullptr) {
                        if (auto lambda_var = var->get_if_lambda()) {
                            if (!render_lambda(handler,
                                               *lambda_var,
                                               ctx,
                                               details::render_lambda_escape::optional,
                                               *comp.tag.section_text,
                                               true))
                            {
                                return walk_control_type::stop;
                            }
                        } else if (!var->is_false()) {
                            render_section(handler, ctx, comp, var);
                        }
                    }
                    return walk_control_type::skip;
                case section_begin_inverted:
                    var = ctx.ctx->get(tag.name);
                    if (var == nullptr || var->is_false()) {
                        render_section(handler, ctx, comp, var);
                    }
                    return walk_control_type::skip;
                case partial:
                    var = ctx.ctx->get_partial(tag.name);
                    if (var != nullptr && (var->is_partial() || var->is_string())) {
                        auto const& partial_result =
                          var->is_partial() ? var->partial_value()() : var->string_value();
                        mustache_view tmpl{this->get_traits()};
                        tmpl.scheme(partial_result);
                        if (!tmpl.is_valid()) {
                            error_msg = tmpl.error_message();
                        } else {
                            tmpl.render(handler, ctx, false);
                            if (!tmpl.is_valid()) {
                                error_msg = tmpl.error_message();
                            }
                        }
                        if (!tmpl.is_valid()) {
                            return walk_control_type::stop;
                        }
                    } else {
                        // todo: add more debugging information here, including:
                        //  - Partial name
                        //  - File
                        //  - Line
                        //  - Column
                        this->logger.error(MUSTACHE_CAT,
                                           "The mustache template requested a partial which we're not able "
                                           "to find; it's getting ignored.");
                    }
                    break;
                case set_delimiter: ctx.delim_set = comp.tag.delim_set; break;
                default: break;
            }

            return walk_control_type::walk;
        }

        constexpr bool render_lambda(
          render_handler const&          handler,
          lambda_type const&             var,
          context_internal<traits_type>& ctx,
          details::render_lambda_escape  escape,
          string_view_type               text,
          bool                           parse_with_same_context) {
            auto render = [this, &ctx, parse_with_same_context, escape](string_view_type txt,
                                                                        bool escaped) -> string_type {
                const auto process_template =
                  [this, &ctx, escape, escaped](mustache_view& tmpl) -> string_type {
                    if (!tmpl.is_valid()) {
                        error_msg = tmpl.error_message();
                        return {};
                    }
                    context_internal<traits_type> render_ctx{ctx}; // start a new line_buffer
                    const auto                    str = tmpl.render(render_ctx);
                    if (!tmpl.is_valid()) {
                        error_msg = tmpl.error_message();
                        return {};
                    }
                    bool do_escape = false;
                    switch (escape) {
                        using enum details::render_lambda_escape;
                        case escape: do_escape = true; break;
                        case unescape: do_escape = false; break;
                        case optional: do_escape = escaped; break;
                    }
                    return do_escape ? escaper(str) : str;
                };
                if (parse_with_same_context) {
                    mustache_view tmpl{this->get_traits()};
                    tmpl.parse(txt, ctx.delim_set);
                    return process_template(tmpl);
                }
                mustache_view tmpl{this->get_traits()};
                tmpl.scheme(txt);
                return process_template(tmpl);
            };
            renderer_type const renderer{
              typename renderer_type::type{render,
                                           alloc::general_alloc_for<typename renderer_type::type>(*this)}
            };
            // todo: in original source, the next line wouldn't run if the user is getting a renderer as input
            render_current_line(handler, ctx.line_buffer, nullptr);
            ctx.line_buffer.data.append(var(text, renderer));
            return error_msg.empty();
        }

        constexpr bool render_variable(
          render_handler const&          handler,
          variable_type const*           var,
          context_internal<traits_type>& ctx,
          bool                           escaped) {
            if (auto val_str = var->get_if_string()) {
                ctx.line_buffer.data.append(escaped ? escaper(*val_str) : *val_str);
            } else if (auto val_lambda = var->get_if_lambda()) {
                using enum details::render_lambda_escape;
                details::render_lambda_escape const escape_opt = escaped ? escape : unescape;
                return render_lambda(handler, *val_lambda, ctx, escape_opt, {}, false);
            }
            return true;
        }

        constexpr void render_section(
          render_handler const&          handler,
          context_internal<traits_type>& ctx,
          component_type&                incomp,
          variable_type const*           var) {
            auto const callback = [&handler, &ctx, this](component_type& comp) -> walk_control_type {
                return render_component(handler, ctx, comp);
            };
            if (var && var->is_non_empty_list()) {
                for (auto const& item : var->list_value()) {
                    // account for the section begin tag
                    ctx.line_buffer.contained_section_tag = true;

                    context_pusher<traits_type> const ctxpusher{ctx, &item};
                    incomp.walk_children(callback);

                    // ctx may have been cleared. account for the section end tag
                    ctx.line_buffer.contained_section_tag = true;
                }
            } else if (var) {
                // account for the section begin tag
                ctx.line_buffer.contained_section_tag = true;

                context_pusher<traits_type> const ctxpusher{ctx, var};
                incomp.walk_children(callback);

                // ctx may have been cleared. account for the section end tag
                ctx.line_buffer.contained_section_tag = true;
            } else {
                // account for the section begin tag
                ctx.line_buffer.contained_section_tag = true;

                incomp.walk_children(callback);

                // ctx may have been cleared. account for the section end tag
                ctx.line_buffer.contained_section_tag = true;
            }
        }
    };

} // namespace webpp::views

#endif // WEBPP_MUSTACHE_VIEW_HPP
